### PR TITLE
add code-block header

### PR DESCRIPTION
**Pull request by Blackbaud-TimPepper**
Show what language is being displayed in the code-block and move the copy-to-clipboard button in to the header so it is always visible. 

https://github.com/blackbaud/stache2/issues/507

### CODE REVIEW

**Comment by Blackbaud-TimPepper** [comment]
image

**Comment by Blackbaud-TimPepper** [comment]
Working design with feedback from Todd:
image

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-ToddRoberts approved this design?

**Comment by Blackbaud-TimPepper** [comment]
Yep! Todd actually suggested the final design changes I made. And I already confirmed that the new design works with the tabbed implementation.

**Comment by Blackbaud-BobbyEarl** [comment]
I realize this behavior is not changing in your PR, but it stands out to me more now that we're visually displaying the language type in the header.  Passing either an unknown `languageType` or not setting the property at all displays "markup" in the header.  Just bringing it up.

The styling for the header seems a little off.  The font-size is 19px and because of the margin around the button, it seems bulkier than it needs to be.  Would it be reduce those to `15px` and have the same spacing as buttons in a toolbar?

I realize this isn't an approved use of a "toolbar," but it seems we'd still want to emulate the style in this case.  https://developer.blackbaud.com/skyux/components/toolbar

**Comment by Blackbaud-ToddRoberts** [comment]
My suggestion was to use sky-subsection-heading for the language text. If the language is not that important to warrant the larger size, and/or largely self-evident with a more subtle reminder appropriate, we could use sky-deemphasized text there.

**Comment by Blackbaud-TimPepper** [comment]
Updated view. Tried to post a screenshot for you guys, but github is refusing to cooperate.

**Pull request merged**
