### PR TITLE
Removed app files except shared

### PR DESCRIPTION
**Pull request by blackbaud-brandonhare**

### CODE REVIEW

**Comment by Blackbaud-BrandonJones** [comment]
If this is the direction we are 100% sure we want to go... then I say sweet.

**Comment by Blackbaud-BrandonJones** [comment]
Actually, maybe we should just remove the components folder?  Keeping the home page/about to use while creating components?    As we are only going to be bundling and exporting the stache file, I don't think it would hurt to keep some front-end matter in this project for dev purposes.

**Comment by blackbaud-brandonhare** [comment]
Yeah @Blackbaud-BrandonJones that's why I put that `index.html` file back in there. That's really all you need for testing purposes.

**Comment by Blackbaud-BrandonJones** [comment]
Unless you're testing routes and layouts :)

**Comment by blackbaud-brandonhare** [comment]
Who needs to do that?

**Pull request merged**
