### PR TITLE
Sidebar Bugs

### PR DESCRIPTION
**Pull request by Blackbaud-BrandonJones**
fixed overflowing long title names in nav, and page jumpy affect with sticky side bar when sidebar is longer than page content

https://github.com/blackbaud/stache2/issues/316
and 
https://github.com/blackbaud/stache2/issues/301

### CODE REVIEW

**Comment by Blackbaud-SteveBrush** [comment]
I get a double scrollbar when using the omnibar:

screen shot 2017-10-16 at 12 07 37 pm

**Comment by Blackbaud-BrandonJones** [comment]
I can't seem to reproduce that?

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BrandonJones Add the following the **skyuxconfig.json**:
```
"omnibar": {
  "experimental": true
}
```

**Comment by Blackbaud-BrandonJones** [comment]
I did that, however I still can't seem to reproduce seeing the double scroll bars.

**Comment by Blackbaud-SteveBrush** [comment]
Double sidebars are gone, but now I see (on small screens):

screen shot 2017-11-29 at 2 00 31 pm

**Pull request merged**
