### PR TITLE
using fa icon instead of svg

### PR DESCRIPTION
**Pull request by Blackbaud-BrandonJones**
Builder does not allow libraries to pull in their own assets, so until that gets resolved we are using a font awesome icon.

### CODE REVIEW

**Comment by blackbaud-brandonhare** [comment]
Didn't we do it this way initially because it wouldn't work on IE11? Does it still work as originally intended?

**Comment by Blackbaud-BrandonJones** [comment]
Before it was an inline SVG string loaded into the element. This is just using an FA icon

**Comment by blackbaud-brandonhare** [comment]
Right, but didn't we have it that way before and it didn't work for some reason? Maybe @Blackbaud-SteveBrush can speak more to that. I could be misremembering.

**Comment by Blackbaud-BrandonJones** [comment]
tested and it works in IE

**Pull request merged**
