### PR TITLE
Updated version

### PR DESCRIPTION
**Pull request by blackbaud-brandonhare**

### CODE REVIEW

**Comment by Blackbaud-BrandonJones** [comment]
I feel like this is an unecessary version bump

**Comment by blackbaud-brandonhare** [comment]
We absolutely want to set the version requirement to 1.3 for the latest. Otherwise the search pipeline stuff will not work.

**Comment by Blackbaud-BrandonJones** [comment]
Yeah, but `^1.2.0` === `^1.3.1`,  the carrot the start of the version number will use the lastest minor release.

**Comment by blackbaud-brandonhare** [comment]
Right, but we want to enforce 1.3 if possible. I'm not saying we should do a new release or anything. I can set it to `^1.3` and be done with it.

**Pull request closed without merging**
